name: Statics tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-format:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: EsLint check
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Build check
        run: npm run build
